import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import assert from 'node:assert/strict'

const appRoot = join(fileURLToPath(new URL('.', import.meta.url)), '..')

function read(relPath) {
  return readFileSync(join(appRoot, relPath), 'utf8')
}

function has(relPath) {
  return existsSync(join(appRoot, relPath))
}

const tests = []
function test(name, fn) {
  tests.push({ name, fn })
}

test('package exposes default, build, and visual smoke scripts', () => {
  const pkg = JSON.parse(read('package.json'))
  assert.equal(pkg.scripts.test, 'node scripts/test-default.mjs')
  assert.equal(pkg.scripts.build, 'electron-vite build')
  assert.ok(pkg.scripts['perf:app-tab']?.includes('scripts/perf-app-tab.mjs'))
  assert.ok(pkg.scripts['visual:smoke']?.includes('scripts/visual-smoke.mjs'))
  assert.ok(pkg.scripts['visual:open']?.includes('scripts/visual-open.mjs'))
})

test('visual automation scripts and docs are present', () => {
  assert.ok(has('scripts/visual-smoke.mjs'), 'missing visual-smoke.mjs')
  assert.ok(has('scripts/visual-open.mjs'), 'missing visual-open.mjs')
  assert.ok(has('scripts/perf-app-tab.mjs'), 'missing perf-app-tab.mjs')
  assert.match(read('scripts/visual-smoke.mjs'), /MAX_VIEWPORT = \{ width: 1400, height: 900 \}/)
  assert.match(read('scripts/visual-smoke.mjs'), /workArea\.width - 80/)
  assert.match(read('scripts/visual-smoke.mjs'), /setZoom\?\.\(1\)/)
  assert.match(read('scripts/visual-open.mjs'), /MAX_VIEWPORT = \{ width: 1400, height: 900 \}/)
  assert.match(read('scripts/visual-open.mjs'), /workArea\.width - 80/)
  assert.match(read('scripts/visual-open.mjs'), /setZoom\?\.\(1\)/)
  assert.match(read('scripts/visual-open.mjs'), /resize <width> <height>/)
  assert.match(read('scripts/visual-open.mjs'), /shotAudit \[name\]/)
  const docs = read('../docs/visual-testing.md')
  assert.match(docs, /visual:open/)
  assert.match(docs, /visual:smoke/)
})

test('resource cards do not create one timer per card for visibility polling', () => {
  const source = read('frontend/src/components/ResourceCard.vue')
  assert.doesNotMatch(source, /setInterval\(\s*\(\)\s*=>\s*\{\s*_visCheck\.value\s*=\s*getVisVersion\(\)\s*\}\s*,\s*300\s*\)/)
  assert.doesNotMatch(source, /\bgetVisVersion\b/)
  assert.doesNotMatch(source, /\bisIndexVisible\b/)
})

test('first-use app and game icon warmup is visible and throttled', () => {
  const source = read('frontend/src/pages/LibraryPage.vue')
  assert.match(source, /iconWarmupVisible/)
  assert.match(source, /runInitialIconWarmup/)
  assert.match(source, /window\.api\.files\.getAppIcon\(resource\.file_path\)/)
  assert.match(source, /window\.api\.files\.saveCover\(resource\.id, icon\)/)
  assert.match(source, /iconWarmupDone\.value\+\+/)
  assert.match(source, /setTimeout\(resolve, 120\)/)
  assert.match(source, /t\('library\.iconWarmup\.title'\)/)
  assert.match(source, /scheduleInitialIconWarmup\(300\)/)
  assert.doesNotMatch(source, /for \(const r of added\) \{\s+window\.api\.files\.getAppIcon/)
})

test('main window wake paths hide the drawer through a single helper', () => {
  const main = read('backend/main.ts')
  assert.match(main, /function showMainWindow\(reason = 'user'\)/)
  assert.match(main, /if \(mainWindow\.isMinimized\(\)\) mainWindow\.restore\(\)/)
  assert.match(main, /drawerWindow\?\.hide\(\)/)
  assert.match(main, /function hideMainToDrawer\(\)/)
  assert.match(main, /ipcMain\.handle\('drawer:openMain', \(\) => \{\s+showMainWindow\('drawer'\)/)
  assert.match(main, /showMainWindow\('second-instance'\)/)
  assert.match(main, /showMainWindow\('activate'\)/)
  assert.match(main, /mainWindow\.on\('focus', \(\) => \{\s+drawerWindow\?\.hide\(\)/)
  assert.match(main, /mainWindow\.on\('minimize', \(\) => \{\s+mainWindow\?\.webContents\.send\('window:wake'\)/)
})

test('quick panel groups can open all resources sequentially', () => {
  const pinboard = read('frontend/src/components/PinBoard.vue')
  const library = read('frontend/src/pages/LibraryPage.vue')
  const zh = read('frontend/src/i18n/locales/zh.ts')
  const en = read('frontend/src/i18n/locales/en.ts')
  assert.match(pinboard, /openMany: \[resources: Resource\[\]\]/)
  assert.match(pinboard, /function openGroupItems\(\)/)
  assert.match(pinboard, /emit\('openMany', children\)/)
  assert.match(library, /@open-many="openResourcesSequentially"/)
  assert.match(library, /async function openResourcesSequentially\(resources: Resource\[\]\)/)
  assert.match(library, /setTimeout\(resolve, 250\)/)
  assert.match(zh, /openAll: '\\u4e00\\u952e\\u542f\\u52a8'/)
  assert.match(en, /openAll: 'Open all'/)
})

test('quick panel resource context menu mirrors normal resource actions', () => {
  const pinboard = read('frontend/src/components/PinBoard.vue')
  const library = read('frontend/src/pages/LibraryPage.vue')
  assert.match(pinboard, /select: \[resource: Resource\]/)
  assert.match(pinboard, /remove: \[resource: Resource\]/)
  assert.match(pinboard, /ignore: \[resource: Resource\]/)
  assert.match(pinboard, /selectCtxItem/)
  assert.match(pinboard, /openCtxAsAdmin/)
  assert.match(pinboard, /showCtxInFolder/)
  assert.match(pinboard, /killCtxItem/)
  assert.match(pinboard, /setCtxPrivate/)
  assert.match(pinboard, /ignoreCtxItem/)
  assert.match(pinboard, /removeCtxItem/)
  assert.match(pinboard, /t\('resource\.detail'\)/)
  assert.match(pinboard, /t\('resource\.admin'\)/)
  assert.match(pinboard, /t\('resource\.showInFolder'\)/)
  assert.match(pinboard, /t\('resource\.setPrivate'\)/)
  assert.match(pinboard, /t\('resource\.ignore'\)/)
  assert.match(pinboard, /t\('resource\.removeFromLibrary'\)/)
  assert.match(library, /@select="onCardSelect"/)
  assert.match(library, /@remove="removeResource"/)
  assert.match(library, /@ignore="ignoreResource"/)
})

test('image and icon loading stays concurrency limited', () => {
  const imageCache = read('frontend/src/utils/image-cache.ts')
  const ipc = read('backend/ipc/index.ts')
  assert.match(imageCache, /const MAX_CONCURRENT = 2\b/)
  assert.match(ipc, /const THUMB_MAX_CONCURRENT = 2\b/)
  assert.match(ipc, /const PS_MAX_CONCURRENT = 1\b/)
})

test('updater compares beta semver versions correctly', () => {
  const updater = read('backend/updater.ts')
  assert.match(updater, /function parseVersion\(version: string\)/)
  assert.match(updater, /normalized\.split\('-', 2\)/)
  assert.match(updater, /prereleasePart\.split\(\/\[\.-\]\/\)/)
  assert.doesNotMatch(updater, /a\.split\('\.'\)\.map\(Number\)/)
  assert.doesNotMatch(updater, /const na = pa\[i\] \|\| 0/)
})

test('manual imports and opens update resource usage', () => {
  const ipc = read('backend/ipc/index.ts')
  const preload = read('backend/preload.ts')
  const apiTypes = read('frontend/src/types/api.d.ts')
  const library = read('frontend/src/pages/LibraryPage.vue')
  const card = read('frontend/src/components/ResourceCard.vue')
  assert.match(ipc, /function touchResourceUsage\(resourceId: string\)/)
  assert.match(ipc, /return recordProcessStart\(resourceId\)/)
  assert.match(ipc, /return touchResourceUsageResult\(addManualResource\(data\)\)/)
  assert.match(ipc, /const result = touchResourceUsageResult\(addManualResource\(item\)\)/)
  assert.match(ipc, /ipcMain\.handle\('files:openPath', async \(_e, filePath: string, meta\?: string, resourceId\?: string\)/)
  assert.match(ipc, /if \(resourceId\) return touchResourceUsage\(resourceId\)/)
  assert.match(ipc, /const resource = getResourceByPath\(filePath\)\s+return resource \? touchResourceUsage\(resource\.id\) : null/)
  assert.match(preload, /openPath: \(filePath: string, meta\?: string, resourceId\?: string\)/)
  assert.match(preload, /openAsAdmin: \(filePath: string, resourceId\?: string\)/)
  assert.match(apiTypes, /openPath: \(filePath: string, meta\?: string, resourceId\?: string\)/)
  assert.match(apiTypes, /openAsAdmin: \(filePath: string, resourceId\?: string\)/)
  assert.match(library, /window\.api\.files\.openPath\(resource\.file_path, resource\.meta, resource\.id\)/)
  assert.match(library, /window\.api\.files\.openAsAdmin\(listMenu\.item\.file_path, listMenu\.item\.id\)/)
  assert.match(library, /window\.api\.files\.openAsAdmin\(heatMenu\.item\.file_path, heatMenu\.item\.id\)/)
  assert.match(card, /window\.api\.files\.openAsAdmin\(props\.resource\.file_path, props\.resource\.id\)/)
  assert.match(ipc, /if \(resourceId\) return touchResourceUsage\(resourceId\)\s+return trackRunningProcess\(targetPath, pid\)/)
  assert.doesNotMatch(ipc, /endsWith\('\\.exe'\)[\s\S]{0,120}recordProcessStart/)
})

test('resource ignore removes by id and read-only installs use writable profile data', () => {
  const ipc = read('backend/ipc/index.ts')
  const preload = read('backend/preload.ts')
  const apiTypes = read('frontend/src/types/api.d.ts')
  const store = read('frontend/src/stores/resources.ts')
  const profiles = read('backend/db/profiles.ts')
  assert.match(preload, /ignore: \(filePath: string, resourceId\?: string\)/)
  assert.match(apiTypes, /ignore: \(filePath: string, resourceId\?: string\)/)
  assert.match(store, /window\.api\.resources\.ignore\(filePath, id\)/)
  assert.match(ipc, /ipcMain\.handle\('resources:ignore', \(_e, filePath: string, resourceId\?: string\)/)
  assert.match(ipc, /if \(resourceId\) removeResource\(resourceId\)/)
  assert.match(ipc, /else removeResourceByPath\(filePath\)/)
  assert.match(profiles, /function canWriteDir\(dir: string\)/)
  assert.match(profiles, /writeFileSync\(probe, 'ok', 'utf8'\)/)
  assert.match(profiles, /function canWriteExistingProfileDb\(dir: string\)/)
  assert.match(profiles, /openSync\(resourceDb, 'r\+'\)/)
  assert.match(profiles, /canWriteDir\(portableDir\) && canWriteExistingProfileDb\(portableDir\)/)
  assert.match(profiles, /const fallbackDir = join\(app\.getPath\('userData'\), 'portable-data'\)/)
  assert.match(profiles, /migrateProfileDataIfNeeded\(portableDir, fallbackDir\)/)
  assert.match(profiles, /copyDirMissing\(join\(fromDir, 'profiles'\), join\(toDir, 'profiles'\)\)/)
})

test('file size is calculated for imports and backfilled safely', () => {
  const queries = read('backend/db/queries.ts')
  const dbIndex = read('backend/db/index.ts')
  const pathSize = read('backend/utils/path-size.ts')
  assert.match(pathSize, /export function getPathSize/)
  assert.match(pathSize, /stat\.isDirectory\(\)/)
  assert.match(pathSize, /readdirSync/)
  assert.match(pathSize, /maxEntries/)
  assert.match(pathSize, /deadlineMs/)
  assert.match(queries, /import \{ getPathSize \} from '\.\.\/utils\/path-size'/)
  assert.match(queries, /INSERT INTO resources \(id, type, title, file_path, cover_path, rating, note, meta, added_at, updated_at, file_size\)/)
  assert.match(queries, /const fileSize = getPathSize\(data\.file_path\)/)
  assert.match(queries, /file_size: resource\.file_size \?\? getPathSize\(resource\.file_path\)/)
  assert.match(dbIndex, /import \{ getPathSize \} from '\.\.\/utils\/path-size'/)
  assert.match(dbIndex, /WHERE file_size IS NULL OR file_size = 0 LIMIT 200/)
  assert.match(dbIndex, /getPathSize\(r\.file_path, \{ maxEntries: 3000, deadlineMs: 500 \}\)/)
  assert.doesNotMatch(queries, /statSync\(data\.file_path\)\.size/)
})

test('default sidebar places documents above applications', () => {
  const navItems = read('frontend/src/config/navItems.ts')
  const settings = read('frontend/src/stores/settings.ts')
  assert.ok(navItems.indexOf("type: 'document'") < navItems.indexOf("type: 'app'"))
  assert.match(settings, /const LEGACY_SIDEBAR_BUILTIN_ORDER = \['all', 'game', 'app'/)
  assert.match(settings, /function migrateSidebarNavOrder\(nav: SidebarNavConfig\[\]\)/)
  assert.match(settings, /migrated\.splice\(appIndex, 0, doc\)/)
  assert.match(settings, /window\.api\.settings\.set\('sidebarNav', JSON\.stringify\(sidebarNav\.value\)\)/)
})

test('low-end defaults keep page size and thumbnail resolution modest', () => {
  const settings = read('frontend/src/stores/settings.ts')
  const library = read('frontend/src/pages/LibraryPage.vue')
  const imageCache = read('frontend/src/utils/image-cache.ts')
  const ipc = read('backend/ipc/index.ts')

  assert.match(settings, /const pageSize = ref\(50\)/)
  assert.match(settings, /const thumbnailSize = ref\(64\)/)
  assert.match(settings, /const glassEnabled = ref\(false\)/)
  assert.match(settings, /const shouldGlass = glassEnabledVal === 'true'/)
  assert.match(settings, /window\.api\.settings\.set\('glassEnabled', 'false'\)/)
  assert.match(settings, /pageSize\.value = parseInt\(pageSizeVal as string\) \|\| 50/)
  assert.match(settings, /window\.api\.settings\.set\('pageSize', '50'\)/)
  assert.match(settings, /window\.api\.settings\.set\('thumbnailSize', '64'\)/)
  assert.match(library, /<option :value="50">50<\/option>/)
  assert.match(library, /settingsStore\.thumbnailSize/)
  assert.match(library, /const THUMB_QUALITY_OPTIONS = \[/)
  assert.match(library, /\{ key: 'smooth', size: 64, labelKey: 'library\.thumbnailSmooth' \}/)
  assert.match(library, /\{ key: 'sharp', size: 256, labelKey: 'library\.thumbnailSharp' \}/)
  assert.match(library, /function setThumbnailQuality\(size: number\)/)
  assert.match(library, /showThumbQualityDropdown\.value = false/)
  assert.doesNotMatch(library, /class="thumb-size-input"/)
  assert.match(imageCache, /export const DEFAULT_GRID_THUMB_SIZE = 64\b/)
  assert.match(imageCache, /window\.api\.files\.readImage\(path, size\)/)
  assert.match(ipc, /const DEFAULT_THUMB_SIZE = 64\b/)
  assert.doesNotMatch(ipc, /const dim = size \?\? 400/)
})

test('document category can create managed notes and profile documents', () => {
  const ipc = read('backend/ipc/index.ts')
  const preload = read('backend/preload.ts')
  const apiTypes = read('frontend/src/types/api.d.ts')
  const library = read('frontend/src/pages/LibraryPage.vue')
  const detailPanel = read('frontend/src/components/ResourceDetailPanel.vue')
  const zh = read('frontend/src/i18n/locales/zh.ts')
  const en = read('frontend/src/i18n/locales/en.ts')

  assert.match(ipc, /type DocumentKind = 'note' \| 'txt' \| 'md' \| 'csv' \| 'docx' \| 'xlsx' \| 'pptx'/)
  assert.match(ipc, /activeProfileDocumentsDir\(kind: DocumentKind\)/)
  assert.match(ipc, /join\(getProfileDir\(manifest\.active\), 'documents'\)/)
  assert.match(ipc, /managed_note: kind === 'note'/)
  assert.match(ipc, /ipcMain\.handle\('documents:create'/)
  assert.match(ipc, /ipcMain\.handle\('documents:readText'/)
  assert.match(ipc, /ipcMain\.handle\('documents:writeText'/)
  assert.match(ipc, /return touchResourceUsageResult\(result\)/)
  assert.match(ipc, /ipcMain\.handle\('documents:touch'/)
  assert.match(ipc, /writeOfficeDocument\(filePath, kind\)/)
  assert.match(preload, /documents: \{/)
  assert.match(preload, /ipcRenderer\.invoke\('documents:create'/)
  assert.match(preload, /ipcRenderer\.invoke\('documents:touch', resourceId\)/)
  assert.match(apiTypes, /documents: \{/)
  assert.match(apiTypes, /touch: \(resourceId: string\)/)
  assert.match(library, /showDocumentCreateEntry/)
  assert.match(library, /class="doc-create-card"/)
  assert.match(library, /:style="\{ '--zoom': cardZoom \}"/)
  assert.match(library, /var\(--card-min-width/)
  assert.doesNotMatch(library, /min-height: 188px/)
  assert.match(library, /window\.api\.documents\.create/)
  assert.match(library, /isManagedLocalNote/)
  assert.match(library, /window\.api\.documents\.readText/)
  assert.match(library, /window\.api\.documents\.writeText/)
  assert.match(library, /await openLocalNote\(result\.resource, false\)/)
  assert.match(library, /const touched = await window\.api\.documents\.touch\(resource\.id\)/)
  assert.match(library, /class="note-editor-modal"/)
  assert.match(library, /@keydown\.ctrl\.s\.prevent="saveLocalNote"/)
  assert.match(library, /class="note-editor-dirty"/)
  assert.match(library, /@click="saveLocalNote"/)
  assert.match(library, /noteTextAreaRef\.value\?\.focus\(\)/)
  assert.match(library, /saveAndCloseLocalNote/)
  assert.match(library, /\.batch-modal-actions \.bm-cancel,[\s\S]*white-space: nowrap/)
  assert.match(library, /\.note-editor-actions \.bm-cancel,[\s\S]*white-space: nowrap/)
  assert.match(library, /@open="openResource"/)
  assert.match(detailPanel, /open: \[resource: Resource\]/)
  assert.match(detailPanel, /function openFile\(\) \{ emit\('open', props\.resource\) \}/)
  assert.match(zh, /createCard: '新建'/)
  assert.match(zh, /saveAndClose: '保存并关闭'/)
  assert.match(en, /createCard: 'New'/)
  assert.match(en, /saveAndClose: 'Save and close'/)
})

test('search includes managed note text content as low priority matches', () => {
  const queries = read('backend/db/queries.ts')
  const ipc = read('backend/ipc/index.ts')
  assert.match(ipc, /INSERT OR REPLACE INTO resource_content/)
  assert.match(ipc, /fetch_status, is_truncated, word_count, fetched_at/)
  assert.match(queries, /JOIN resource_content rc ON rc\.resource_id = r\.id/)
  assert.match(queries, /content_hits=\$\{contentRows\.length\}/)
  assert.match(queries, /function readSearchableTextDocument/)
  assert.match(queries, /ext !== '\.md' && ext !== '\.txt'/)
  assert.match(queries, /stat\.size > 1024 \* 1024/)
  assert.match(queries, /text_file_hits/)
  assert.match(queries, /rows\.push\(row\)/)
})

let failed = 0
for (const { name, fn } of tests) {
  try {
    fn()
    console.log(`ok - ${name}`)
  } catch (error) {
    failed += 1
    console.error(`not ok - ${name}`)
    console.error(error?.stack || error)
  }
}

if (failed > 0) {
  console.error(`${failed} test(s) failed`)
  process.exit(1)
}

console.log(`${tests.length} test(s) passed`)
